export {CPrivateRoute} from '../components/PrivateRoute'
export {AuthPage} from './AuthPage'
export {CategoriesPage} from './CategoriesPage'
export {CartPage} from './CartPage'
export {CategoryGoodsPage} from './CategoryGoodsPage'
export {GoodPage} from './GoodPage'
export {UserOrdersPage} from './UserOrdersPage'
export {OrderPage} from './OrderPage'
