module.exports = {
    
    CHANGE_GOOD: "CHANGE_GOOD",
    ADD_GOOD: "ADD_GOOD",
    REMOVE_GOOD: "REMOVE_GOOD",
    CLEAR_CART: "CLEAR_CART",
    
    PENDING: "PENDING",
    RESOLVED: "RESOLVED",
    REJECTED: "REJECTED",

    SEND_PENDING: "SEND_PENDING",
    SEND_RESOLVED: "SEND_RESOLVED",
    SEND_REJECTED: "SEND_REJECTED",

    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    
}